version: "3"

volumes:
  mysql:

services:
  db:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    build: ./
    ports:
      - "3306:3306"
