version: '3'

volumes:
  mysql:

services:
  db:
    container_name: spring_react_mysql
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    build: ./
    ports:
      - '9001:3306'
